spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gb_hibernate?useSSL=false
    username: root
    password: pass
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/liquibase-changeLog.xml

welcome:
  to: 'the-hell'